model:
  arch: mini_gpt4_llama_v2
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  low_resource: False
  image_size: 224
  end_sym: "</s>"
  llama_model: "mistralai/Mistral-7B-Instruct-v0.2"
  ckpt: "checkpoints/video_captioning_mistral_checkpoint_last.pth" # set the checkpoint to start the training from
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 7200


datasets:
  video_chatgpt: #99378 row  - 13224 video
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 200


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 50
  num_workers: 16
  warmup_steps: 875
  iters_per_epoch: 875

  seed: 42
  output_dir: "training_output/pretrained_video_instruct/mistral"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
