model:
  arch: mini_gpt4_llama_v2
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 256
  low_resource: False
  image_size: 224
  end_sym: "</s>"
  # llama_model: "/home/develop/fyy/MiniGPT4-video-main/merge_pretraints"
  llama_model: "/home/develop/fyy/MiniGPT4-video-main/Llama-2-7b-chat-hf"
  # ckpt: "/home/develop/fyy/MiniGPT4-video-main/minigpt4/training_output/pretrained_video_instruct/llama2/202405121421/checkpoint_1.pth" # set the checkpoint to start the training from
  ckpt: "/home/develop/fyy/MiniGPT4-video-main/ego-sentiment/weights/1video_llama_checkpoint_changed.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 3600
  need_speech: True
  # need_speech: False
  finetune: "/home/develop/fyy/MiniGPT4-video-main/finetuned.pth"


datasets:
  video_chatgpt: #99378 row  - 13224 video
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 200
    need_speech: True
    # need_speech: False
    wav_base: '/home/develop/fyy/MovieChat-main/fyy/all_videos/mini-useful_wav16k'
    # wav_base: "/home/develop/fyy/MiniGPT4-video-main/msvd/wav_16k"
    dataset: 'ego-sentiment'
    # add_subtitles: False
    add_subtitles: True
run:
  task: image_text_pretrain
  # optimizery
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  # max_epoch: 50
  max_epoch: 6
  num_workers: 1
  warmup_steps: 100
  # warmup_steps: 1000
  # iters_per_epoch: 1000
  iters_per_epoch: 1000
  # iters_per_epoch: 100

  seed: 42
  output_dir: "training_output/pretrained_video_instruct/llama2"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
