model:
  arch: mini_gpt4_llama_v2
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 256
  low_resource: True
  image_size: 224
  end_sym: "</s>"
  # llama_model: "/home/develop/fyy/MiniGPT4-video-main/new_merge"
  llama_model: "/home/develop/fyy/MiniGPT4-video-main/Llama-2-7b-chat-hf"
  ##
  ckpt: "/home/develop/fyy/MiniGPT4-video-main/ego-sentiment/weights/3checkpoint_norm_no_speech_8.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 3600
  ##
  # need_speech: True
  need_speech: False
  finetune: "/home/develop/fyy/MiniGPT4-video-main/finetuned.pth"


datasets:
  video_chatgpt: #99378 row  - 13224 video
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 200
    ##
    dataset: 'ego-sentiment'
    # dataset: "msvd"
    add_subtitles: True
    # add_subtitles: False
    # need_speech: True
    need_speech: False
    wav_base: '/home/develop/fyy/MovieChat-main/fyy/all_videos/mini-useful_wav16k'
run:
  seed: 42
  amp: True
